// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://boydxqmsofpdftikcwsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJveWR4cW1zb2ZwZGZ0aWtjd3NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NjQ5NDcsImV4cCI6MjA3MDA0MDk0N30.ypW1jEsF0A1KmcqNnAqjW8faamMknF9GkJEB9tCHCj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});